CREATE TABLE client(
    username varchar(20) NOT NULL,
    passwd varchar(20) NOT NULL,
    address varchar(20) NOT NULL,
    city varchar(20) NOT NULL,
    province varchar(30) NOT NULL,
    postalcode varchar(10) NOT NULL,
    PRIMARY KEY(username),
    UNIQUE(username)
);

CREATE TABLE publisher(
    pub_name varchar(20) NOT NULL,
    address varchar(20) NOT NULL,
    email varchar(30) NOT NULL,
    bank varchar(30) NOT NULL,
    province varchar(30) NOT NULL,
    city varchar(20) NOT NULL,
    PRIMARY KEY(pub_name),
    UNIQUE(pub_name)
);

CREATE TABLE book(
    title varchar(50) NOT NULL,
    isbn varchar(20) NOT NULL,
    pub varchar(20) NOT NULL,
    pages int NOT NULL,
    price numeric(10,2) NOT NULL,
    pubcut numeric(5,2) NOT NULL,
    stock int NOT NULL,
    FOREIGN KEY(pub) REFERENCES publisher(pub_name),
    PRIMARY KEY(isbn),
    UNIQUE(isbn)
);

CREATE TABLE purchase(
    user_id varchar(20) NOT NULL,
    book_id varchar(20) NOT NULL,
    purchase_date date NOT NULL,
    status varchar(30) NOT NULL,
    shipping varchar(200) NOT NULL,
    billing varchar(100) NOT NULL,
    amount int NOT NULL,
    purchase_id int GENERATED BY DEFAULT AS IDENTITY,
    FOREIGN KEY(user_id) REFERENCES client(username),
    FOREIGN KEY(book_id) REFERENCES book(isbn),
    PRIMARY KEY(purchase_id)
);

CREATE TABLE phone(
    pub varchar(20) NOT NULL,
    phone varchar(16) NOT NULL,
    FOREIGN KEY(pub) REFERENCES publisher(pub_name)
);

CREATE TABLE genre(
    book_id varchar(20) NOT NULL,
    genre varchar(10) NOT NULL,
    FOREIGN KEY(book_id) REFERENCES book(isbn)
);


CREATE TABLE author(
    book_id varchar(20) NOT NULL,
    author varchar(20) NOT NULL,
    FOREIGN KEY(book_id) REFERENCES book(isbn)
);